### ISSUE TITLE
Timing interaction between Address-Request and Address-Assign capsule and the Connect-IP request

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#54] opened 2022-07-01 09:50 UTC
So there appear to exist some downside with the timing of the interactions when one want to use Address-Request capsule. So the basic problem is simply that the proxy will assign an address prior to the Address-Request capsule has been received, thus preventing the proxy from processing the request in the right context.  

So lets assume that the client has already created one connect-IP request with a limited scope and been assigned IP-A. Then it want to make an additional request for another limited scope proxying and would like to get the same address assigned. Due to the separation between the HTTP request for the Connect-IP and the capsule Address-Request a server can actually process the whole HTTP request prior to receiving the Address-Request. Resulting potentially in that another IP address assignment (IP-B) be provided to the client, despite it asking for IP-A to be assigned also to the request. 

So does the HTTP request needs an indicator parameter to tell the proxy to wait for one or more "request" capsules from the client before processing the request?

**Comment by DavidSchinazi** [comment] 2022-07-01 17:23
Out of curiosity, in what scenario would the client "like to get the same address assigned"? It makes sense for the proxy to decide to reuse addresses to save its address pool when the scoping allows it, but why would the client care?

**Comment by tfpauly** [comment] 2022-07-01 17:36
I could imagine this happening if the client was trying to resume some previous session that it lost due to an outage? Seems to be niche, but it's certainly possible.

**Comment by gloinul** [comment] 2022-07-04 07:29
So the most obvious use case for this is to request iproto= CMP in combination with for example UDP. Then getting ICMP for another IP address then the one you already have UDP for is mostly useless if you intended to use the ICMP messages for hints when things fails for you UDP based protocol. I would note that for an endpoint liking to do P2P NAT traversal stuff getting an IP address rather than using Connect-UDP does make sense as it ensure the client has control. It enables the IP address for its UDP traffic to be Endpoint-Independent Mapping (RFC4787). This might be niche usages but I would like to avoid creating artificial barriers that makes things impossible or at least hard to realise.

**Comment by DavidSchinazi** [comment] 2022-07-06 19:10
Thanks, this makes sense.

Should we suggest that clients bundle the ADDRESS_REQUEST in the same packet as the HTTP headers and suggest that servers check for those before responding?

**Comment by gloinul** [comment] 2022-07-07 13:59
> Should we suggest that clients bundle the ADDRESS_REQUEST in the same packet as the HTTP headers and suggest that servers check for those before responding?

I am still worried that this creates issues as your request may not fit in a single packet to begin with. My solution would be to actually move the address request part into the HTTP request itself as header field. That would ensure an atomic operation and no risk for errors.

**Comment by achernya** [comment] 2022-07-07 15:30
Magnus, is your proposal to require, or to allow as an option, for the address request to be moved into the HTTP request? Why not bundle the capsules over a reliable delivery mechanism instead?

**Comment by gloinul** [comment] 2022-07-07 16:01
> Magnus, is your proposal to require, or to allow as an option, for the address request to be moved into the HTTP request? Why not bundle the capsules over a reliable delivery mechanism instead?

I first of all want to ensure that you can do a request that ensures that for those cases when it is necessary to interpret the Connect-IP request in the context of desired IP address it can done. Without uncertainties or requiring to have wait time to see if there are capsules incoming. So I think primarily allow as an option. I think a question back to your usages, do you have cases where one would need additional capsules to correctly interpret the option. Should we look for an other solution than the one I proposed to better cover the necessary functionality?

**Comment by achernya** [comment] 2022-07-07 16:18
I want to be able to continue to do ADDRESS_ASSIGN capsules during the lifetime of the connection to support e.g., IPv6 Privacy extensions but without having to delegate the entire subnet. So I don't want to move to header-only.

**Comment by achernya** [comment] 2022-07-07 19:48
Is there any reason to not bring back the `ATOMIC` capsules?

**Comment by DavidSchinazi** [comment] 2022-07-07 19:54
The only reason I can think of is to keep the core spec as short and simple as possible. But if we think this is an important feature then I'm not opposed to bringing back `ATOMIC`.

**Comment by achernya** [comment] 2022-07-07 20:01
I agree with the sentiment of keeping the core spec short and simple, but the trade-off is also knowing what the minimum viable featureset we can always rely on is. If we conclude that `ATOMIC` capsules are in that set, that IMHO weighs towards including them. Given that both Magnus and I have now presented use-cases for atomicity, I think this finally swings towards including?

**Comment by DavidSchinazi** [comment] 2022-07-07 21:38
I agree with that

**Comment by mirjak** [comment] 2022-07-08 13:50
I agree I with Magnus and think we should specify a ay to add the address request to the http request. If there is a timing dependency it's better to put all needed information into the same request than specifying extra and complex logic to achieve the same in hindsight. That doesn't mean that we don't need the address request capsule (for later use in the connection). I think we need both.

**Comment by DavidSchinazi** [comment] 2022-07-08 15:48
I dislike having two ways of conveying the same thing. How about a simple HTTP header `connect-ip-bundled-capsules = 4` that tells the receiver that there are 4 capsules coming right after the HTTP headers?

**Comment by tfpauly** [comment] 2022-07-08 16:00
I'd prefer to avoid "atomic capsule" starts and ends. If we need a way to guarantee inclusion of the local address in the first request, having it be in the HTTP request makes sense, either as another URI parameter, a header to say what address you want, or a header to say you will have capsules that need to be parsed before responding.

That latter option is flexible, certainly, but could be over-engineered.

Another option is to tightly scope a header to the use case we think is relevant. If the use case is "please use the same address as this other request stream I already have for connect-ip or connect-UDP", we could just have a header to say for any connect- request that it is entangled with another and should share some properties. I could imagine this even without CONNECT-IP. Today with private relay, we have to ask the proxies to prefer to use the same local IP for everything in a connection from the client, but letting the client choose what gets grouped might be even nicer. 

This option also lets you issue multiple requests, say they should share, without needing to know exactly which IP any of them will get assigned first.

**Comment by DavidSchinazi** [comment] 2022-07-08 16:42
Unfortunately requests and headers are end-to-end but streams are hop-by-hop so there is no easy HTTP way to have a request refer to another request.

I'd be supportive of adding the `connect-ip-bundled-capsules = 4` header but I'd push back on adding a header that duplicates a capsule.

This is starting to feel like something best-served by an extension

**Comment by tfpauly** [comment] 2022-07-08 17:44
You could solve the correlation by having a "group" ID that you attach to all related requests. No need to refer by stream ID.

**Comment by DavidSchinazi** [comment] 2022-07-08 17:56
What is the scope of a group ID? Connection? If so it's the same as stream IDs.

**Comment by tfpauly** [comment] 2022-07-08 18:59
I think this should be some extension, but it could be a UUID too, doesn't need to be connection specific.

**Comment by DavidSchinazi** [comment] 2022-07-08 23:21
Ah, thanks. Yeah UUID would work.

Back to the issue at hand, I propose this feature request get moved to an extension.

**Comment by achernya** [comment] 2022-07-08 23:38
All of these alternatives strike me as much more complex that the semantics of `ATOMIC`. I'd rather we have a single mechanism even if it's slightly more powerful and restrain it's use than try to invent new ways to solve each problem that arises.

**Comment by tfpauly** [comment] 2022-07-09 00:27
Atomic doesn't help coordinate between requests on different streams, etc, so it's not really solving the full problem here. Either way, I think this is something to defer to an extension.

**Comment by achernya** [comment] 2022-07-09 00:29
Headers don't solve that problem either, so I'm not sure that argument really makes sense in this context. Cross stream coordination seems out of scope to me.

**Comment by gloinul** [comment] 2022-07-11 10:07
So you are taking this into directions I did not intended. I am just asking for how to ensure that the server does not answers the client's request prior to having received any capsules if they are coming. And the real issue is that the server can't know unless the client either includes the corresponding data in the HTTP request or includes an indication that there will be capsules that are relevant to the requests. 

So, my main worry is if waiting for capsule to answer will actually work if there are an HTTP 1.x intermediary connection on the path between the client and the server. I guess its is sending the capsule after the request and hope it makes it. Because to my understanding in HTTP datagram the peer does not expect any data to arrive so it must be upgraded. Thus, one can end up in cases where the capsule protocol does not make it, where the HTTP request does arrive.

**Comment by mirjak** [comment] 2022-07-11 16:07
While we might want to have a more generic extension to relate information to multiple requests, I think the problem Magnus describes needs a solution now. The problem is that there is a dependency between replying/react to a connect request and potentially information send in capsules. The best solution is to send this information together with the connection request instead. I don't see any concern to have a http request or URI parameter and the capsule. What's the problem about that?

**Comment by achernya** [comment] 2022-07-11 18:25
Magnus, what is "the client's request" here? Is it the extended-connect itself, or a response to a capsule? If it's the former, the server can't know what capsules, if any, are coming at this time, as we haven't yet established we are using the capsule protocol. If it's the latter, `ATOMIC` capsules trivially solve this, as you cannot process any of the requests until the `ATOMIC_END` capsule is received.

Mirja, 

> I don't see any concern to have a http request or URI parameter and the capsule. What's the problem about that?

I'd like to avoid having 2 ways to do things, especially since putting it on the HTTP request is a less-generic mechanism and cannot be reused during the connection, whereas capsules can. If we believe this feature is important, I'd like us to solve it generically, rather than special-casing one use case we are aware of right now.

**Comment by gloinul** [comment] 2022-07-11 19:09
So the client's request is the HTTP request that is only complete in semantics when combined with the request-address capsule.

**Comment by achernya** [comment] 2022-07-11 19:18
Sorry Magnus, I'm not sure I understand what you're trying to say. I don't think we can enforce a semantic that a higher-level HTTP request is only complete after some bytes on the then-negotiated protocol have been exchanged.

**Comment by gloinul** [comment] 2022-07-11 19:30
> Sorry Magnus, I'm not sure I understand what you're trying to say. I don't think we can enforce a semantic that a higher-level HTTP request is only complete after some bytes on the then-negotiated protocol have been exchanged.

But this is really the issue, there is currently no way for a client to ask the server to only provide a targeted connect-IP forwarding if the IP address it can provide is the one the client asks for in a consistent way. My interpretation of the specification is that either;
1) the server will never take the request-addr into account initially for the request, and interpret the request-addr after it has created a Connect-IP forwarding
2) the server will sometime take the request-addr into account by have a short delay awaiting for the request-addr capsule, which may or may not make it in time for the implementation specific timer.

This non-consistency or failure to address a use case that I think several was interested in resolving is a real problem. A problem I think we will have to take with us to the meeting.

**Comment by achernya** [comment] 2022-07-11 20:18
> there is currently no way for a client to ask the server to only provide a targeted connect-IP forwarding if the IP address it can provide is the one the client asks for in a consistent way

This ultimately stems from us not having an explicit capsule/message to indicate that forwarding should actually begin. Right now it's implicit as soon as the capsule is assembled with the IP addressing information. This is leading to your proposal to stick more things onto the initial request, whereas I believe the correct solution is to add more capabilities to the capsule protocol to express these scenarios.

**Comment by DavidSchinazi** [comment] 2022-07-12 16:16
> I will consider what you are saying.

I hope so, constructive discussion relies on all of us considering what the others are saying 🙂

> However, I will note that we might have different goals. I do have a need for identifiable streams that can be referred to in extension signalling. Using capsules does not achieve that with the current design as the stream identifier comes from the HTTP request, not the subsequent capsule signalling.

Given that we're all trying to solve slightly different problems here, I see two outcomes:
* we have one simple generic solution that happens to work for everyone
* we punt this to more specific extensions since these problems are not generic

**Comment by gloinul** [comment] 2022-07-13 08:26
> Given that we're all trying to solve slightly different problems here, I see two outcomes:
> 
> * we have one simple generic solution that happens to work for everyone
> * we punt this to more specific extensions since these problems are not generic

So I think the issue here is what we consider core functionality. My observation here is that Alex is promoting functionality that will make it easy to make quite rich things for the network tunnelling use case that you are promoting. While I am bringing up something that to me appear core for the single endpoint tunnelling. So I think we actually need to understand the issues as well as what usage and how usable this is in common and how to handle where the different use cases actually benefits from having the functionality in different places.

**Closed** 2022-08-12 19:47 UTC
Labels: needs discussion
